### ISSUE TITLE
Last task menu entry opens "about" popup

### ISSUE THREAD

**Issue by Sweeet** [idietmoran/Display-Lock#84]
Selecting the last entry in the right click context menu on the task bar it opens the about pop up window.

develop/2.1.0.33 is the version this bug is in.

**Comment by idietmoran** [comment]
This can be fixed by changes the numeric value of the items in the menu to something greater than resource items.

**Comment by idietmoran** [comment]
Fixed in commit f39557b63193f3c486f3815be3c941dbe62522a5
